export const JiraSectorOptions = [
  {
    value: "ADMINISTRAÇÃO",
    label: "ADMINISTRAÇÃO",
    color: "#DA0037",
  },
  { value: "ALMOXARIFADO", label: "ALMOXARIFADO", color: "#DA0037" },
  { value: "COMPRAS", label: "COMPRAS", color: "#DA0037" },
  {
    value: "COMERCIAL - Managers",
    label: "COMERCIAL",
  },
  {
    value: "SAC - Managers",
    label: "SAC",
    color: "#DA0037",
  },
  {
    value: "CUSTOS",
    label: "CUSTOS",
  },
  { value: "DP", label: "DP - DEPARTAMENTO PESSOAL", color: "#DA0037" },
  {
    value: "DTD - Managers",
    label: "DTD - DEPARTAMENTO TÉCNICO DE DESENVOLVIMENTO",
    abbreviation: "DTD",
    color: "#1597E5",
  },
  {
    value: "DTE - Managers",
    label: "DTE - DEPARTAMENTO TÉCNICO DE ELÉTRICA",
    abbreviation: "DTE",
    color: "#1597E5",
  },
  {
    value: "DTI - Managers",
    label: "DTI - DEPARTAMENTO TÉCNICO DE INSTALAÇÕES",
    abbreviation: "DTI",
    color: "#1597E5",
  },
  {
    value: "DTM - Managers",
    label: "DTM - DEPARTAMENTO TÉCNICO DE MÁQUINAS",
    abbreviation: "DTM",
    color: "#1597E5",
  },
  {
    value: "DTP - Managers",
    label: "DTP - DEPARTAMENTO TÉCNICO DE PRODUÇÃO",
    abbreviation: "DTP",
    color: "#1597E5",
  },
  {
    value: "COMERCIAL - Global",
    label: "DTC - DEPARTAMENTO TÉCNICO COMERCIAL",
    abbreviation: "DTC",
    color: "#1597E5",
  },
  { value: "EXPEDIÇÃO", label: "EXPEDIÇÃO", color: "#DA0037" },
  { value: "FABRICAÇÃO", label: "FABRICAÇÃO", color: "#DA0037" },
  {
    value: "FINANCEIRO",
    label: "FINANCEIRO",
    color: "#DA0037",
  },
  { value: "RH", label: "RH - RECURSOS HUMANOS", color: "#DA0037" },
  { value: "MANUTENÇÃO", label: "MANUTENÇÃO", color: "#DA0037" },
  { value: "MARCENARIA", label: "MARCENARIA", color: "#DA0037" },
  { value: "MARKETING", label: "MARKETING", color: "#DA0037" },

  {
    value: "MONT. ELÉTRICA",
    label: "MONTAGEM ELÉTRICA",
    color: "#DA0037",
    abbreviation: "MONT. ELÉTRICA",
  },
  {
    value: "MONT. MECÂNICA",
    label: "MONTAGEM MECÂNICA",
    color: "#DA0037",
    abbreviation: "MONT. MECÂNICA",
  },
  {
    label: "OBRAS E INSTALAÇÕES",
    value: "OBRAS E INSTALAÇÕES",
  },
  {
    value: "PCP - Managers",
    label: "PCP - PLANEJAMENTO CONTROLE DE PRODUÇÃO",
    abbreviation: "PCP",
    color: "#519259",
  },
  { value: "PINTURA", label: "PINTURA", color: "#DA0037" },
  { value: "PORTARIA", label: "PORTARIA", color: "#DA0037" },
  {
    value: "PROCESSOS",
    label: "PROCESSOS",
  },
  {
    value: "PRODUÇÃO - Managers",
    label: "PRODUÇÃO",
  },
  {
    value: "QUALIDADE - Managers",
    label: "QUALIDADE",
  },
  {
    value: "DIRETORIA",
    label: "DIRETORIA",
  },
  {
    value: "SEGURANÇA DO TRABALHO",
    label: "SST - SEGURANÇA DO TRABALHO",
    abbreviation: "SST",
    color: "#DA0037",
  },
  { value: "IMPORTAÇÃO", label: "IMPORTAÇÃO", color: "#DA0037" },
  { value: "TI", label: "TI - TECNOLOGIA DA INFORMAÇÃO", color: "#DA0037" },
  { value: "TECNOLOGIA DE PROCESSOS", label: "TP - TECNOLOGIA DE PROCESSOS", color: "#DA0037" },
  { value: "USINAGEM", label: "USINAGEM", color: "#DA0037" },
];