const CodeRncOptions = [
  { label: "Divergência de Estoque - DET", value: "DET" },
  { label: "Erro na Separação de Material - ESM", value: "ESM" },
  { label: "Falta de Material de Consumo - FMC", value: "FMC" },
  { label: "Atraso na Entrega de MP - AEM", value: "AEM" },
  { label: "Falha no Processo de Follow-up - FPF", value: "FPF" },
  { label: "Alteração de Projeto - APR", value: "APR" },
  { label: "Desenho Desatualizado - DDE", value: "DDE" },
  { label: "Erro de Cadastro - ERC", value: "ERC" },
  { label: "Erro de Projeto - EPR", value: "EPR" },
  { label: "Erro na Ficha Técnica - EFT", value: "EFT" },
  { label: "Erro na Lista Básica - ELB", value: "ELB" },
  { label: "Erro no Desenho - EDE", value: "EDE" },
  { label: "Erro no Esquema Elétrico - EEE", value: "EEE" },
  { label: "Erro no Plano de Corte - EPC", value: "EPC" },
  { label: "Falta Especificação no Desenho - FED", value: "FED" },
  { label: "Lista Básica Desatualizada - LBD", value: "LBD" },
  { label: "Plano de Corte Desatualizado - PCD", value: "PCD" },
  { label: "Protótipo - PRO", value: "PRO" },
  { label: "Embalagem Inadequada - EIN", value: "EIN" },
  { label: "Falha no Transporte - FNT", value: "FNT" },
  { label: "Manual Não Enviado - MNE", value: "MNE" },
  { label: "Danos Durante o Corte Laser - DCL", value: "DCL" },
  { label: "Erro de Furação na Fabricação - EFF", value: "EFF" },
  { label: "Erro de Interpretação do Desenho - EID", value: "EID" },
  { label: "Erro nas Dimensões do Item Produzido - EIP", value: "EPF" },
  { label: "Falha na Solda - EPS", value: "EPS" },
  { label: "Peça Com Oxidação - POX", value: "POX" },
  { label: "Peça Empenada na Fabricação - PEF", value: "PEF" },
  { label: "Fornecedor - FOR", value: "FOR" },
  { label: "Matéria Prima Enviada Não Conforme - MNC", value: "MNC" },
  { label: "Acondicionamento Inadequado - AIN", value: "AIN" },
  { label: "Avaria nas Dependências da Sangati - ADS", value: "ADS" },
  { label: "Desaparecimento de Peça - DEP", value: "DEP" },
  { label: "Erro de Nota Fiscal - ENF", value: "ENF" },
  { label: "Erro na Especificação do Material - EEM", value: "EEM" },
  { label: "Erro Operacional - EOP", value: "EOP" },
  { label: "Falha na Comunicação - FCO", value: "FCO" },
  { label: "Falha de Máquina - FMA", value: "FMA" },
  { label: "Falha no Processo - FPR", value: "FPR" },
  { label: "Instrumento Não Calibrado - INC", value: "INC" },
  { label: "Matéria Prima Danificada - MPD", value: "MPD" },
  { label: "Outros - OUT", value: "OUT" },
  { label: "Perda de Desenho/Projeto - PDP", value: "PDP" },
  { label: "Perda de Peça - PPE", value: "PPE" },
  { label: "Processo de Trabalho - PTR", value: "PTR" },
  { label: "Produto Danificado - PDA", value: "PDA" },
  { label: "Erro de Interpretação de Esquema - EIE", value: "EIE" },
  { label: "Esquema de Montagem Incorreto - EMI", value: "EMI" },
  { label: "Manual Desatualizado - MDE", value: "MDE" },
  { label: "Manual Não Disponível - MND", value: "MND" },
  { label: "Acabamento Inadequado - ACI", value: "ACI" },
  { label: "Erro de Montagem - EDM", value: "EDM" },
  { label: "Pintura Arranhada na Montagem - PAM", value: "PAM" },
  { label: "Erro Tempo Padrão - ETP", value: "ETP" },
  { label: "Falha no Acompanhamento da Produção - FAP", value: "FAP" },
  { label: "Falha no Planejamento - FPL", value: "FPL" },
  { label: "Camada de Tinta Baixa - CTB", value: "CTB" },
  { label: "Escorrimento de Tinta - ESC", value: "ESC" },
  { label: "Falta de Aderância da Tinta - FAT", value: "FAT" },
  { label: "Fervura da Tinta - FNT", value: "FDT" },
  { label: "Olho de Peixe (CRATERAS) - OPE", value: "OPE" },
  { label: "Auditoria Externa ISO 9001", value: "Auditoria Externa ISO 9001" },
  { label: "Auditoria Interna Qualidade", value: "Auditoria Interna Qualidade" },
  { label: "Falta de Procedimento - FPR", value: "FDP" },
  { label: "Indicador - IND", value: "IND" },
  { label: "Não Atendimento aos Requisitos do Cliente - NAR", value: "NAR" },
  { label: "Não Cumprimento do Procedimento - NCP", value: "NCP" },
  { label: "Reclamações de Clientes - RCL", value: "RCL" },
  { label: "Reunião de Análise Crítica - RAC", value: "RAC" },
  { label: "Falta de Treinamento - FTR", value: "FTR" },
  { label: "Porosidade na Peça - PNP", value: "PNP" },
  { label: "Usinagem Fora das Especificações - UFE", value: "UFE" },
  { label: "Solda não realizada", value: "SNR" },
  { label: "Acabamento não realizado", value: "ANR" },
  { label: "Abertura de rosca não realizada", value: "ARR" },
  { label: "Aplicação de tinta fora da especificação", value: "AFE" },
  { label: "Desplacamento de tinta", value: "DDT" },
  { label: "Material enviado errado ao cliente", value: "MEC" },
  { label: "Falha no processo de pintura", value: "FPI" },
];