import { CustomFields } from "@/shared/constants/jira/jira-custom-fields";

export const WFTQ = [
    "issuetypeid",
    "status",
    "reporter",
    "assignee",
    CustomFields.SETOR_EMITENTE.id,
    CustomFields.SETOR_ORIGEM.id,
    CustomFields.TIPO_RELATORIO.id,
    "idealizers",
    "priority",
    CustomFields.COD_RELATORIO.id,
    CustomFields.CLIENTE.id,
    CustomFields.OP.id,
    CustomFields.PEDIDO.id,
    CustomFields.DISPOSICAO.id,
    CustomFields.ITEM_RNC.id,
    CustomFields.IDENTIFICADO_EM.id,
    CustomFields.COMPONENTE.id,
    CustomFields.PRAZO.id,
    "description",
    CustomFields.QTD_ITEM.id,
    "comments",
    CustomFields.ENVIA_MATERIAL_CLIENTE.id,
    CustomFields.COD_QTD.id,
    CustomFields.TIPO_FRETE.id,
    CustomFields.REG_PED_GARANTIA.id,
    "attachments",
    "subtasks",
    "subtaskTable",
    "subtasksList",
]